### ISSUE TITLE
Modify Makefile to allow DOCKER_HUB_ID to be overridden by env var

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-cpp#2]
In the future we plan to have a more advanced CI/CD process and allowing the `DOCKER_HUB_ID` to be overridden by an environment variable will needed. 

We should change 
``` 
DOCKERHUB_ID:=ibmosquito
``` 
to the following
```
DOCKER_HUB_ID ?= ibmosquito
```

**Comment by c-bommu** [comment]
Can I get assigned to this issue?

**Comment by joewxboy** [comment]
You got it, @c-bommu

**Comment by joewxboy** [comment]
How's your progress, @c-bommu?  Let me know if you have any questions.
